language: python
python:
  - 3.6.2

services:
  - docker
  - docker-compose

install:
  - docker-compose -f docker-compose-prod.yml build

script:
  - docker-compose -f docker-compose-prod.yml run --rm web python3 manage.py test
