language: python
python:
  - 3.6.2

services:
  - docker
  - docker-compose

install:
  - docker-compose -f docker-compose-prod.yml build

script:
  - docker-compose -f docker-compose-prod.yml run --rm web ./wait-for-it.sh db:5432 -- python3 manage.py test

deploy:
  provider: script
  script: bash docker_push
  on:
    all_branches: true

