version: '2'

volumes:
  dbvolume:
  ipython:
  static_volume:
  node_module:

services:
  db:
    image: postgres:9.6
    ports:
      - 5543:5432
    env_file:
      - .env
    volumes:
      - dbvolume:/var/lib/postgresql/data/
  web:
    build: ./backend
    restart: always 
    expose:
      - 8000
    env_file:
      - .env
    environment:
      - DEBUG=1
    volumes:
      - ./backend/:/usr/src/app/
      - ./Videos/:/usr/src/app/Videos
      - static_volume:/usr/src/app/staticfiles
      - /static/
      - ipython:/root/.ipython
    command: bash -c "python3 /usr/src/app/manage.py migrate && python3 /usr/src/app/manage.py populatedb && python3 /usr/src/app/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - ./backend/:/usr/src/app/
      - ./Videos/:/usr/src/app/Videos
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/usr/src/app/
      - node_module:/usr/src/app/frontend/node_modules/
    command: bash -c "npm install && npm start"
    depends_on:
      - web
    ports:
      - 3000:3000

