version: '2'

volumes:
  dbvolume:
  ipython:
services:
  db:
    image: postgres:9.6
    ports:
      - 5543:5432
    env_file:
      - .env
    volumes:
      - dbvolume:/var/lib/postgresql/data/
  web:
    build: .
#    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate --run-syncdb && python3 manage.py runserver 0.0.0.0:8002"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MyURLSaverProdKey=1111111
    volumes:
      - .:/code
      - /static/
      - ipython:/root/.ipython
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
